-- MySQL Script generated by MySQL Workbench
-- Wed May  1 18:53:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sporters_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sporters_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sporters_db` DEFAULT CHARACTER SET utf8 ;
USE `sporters_db` ;

-- -----------------------------------------------------
-- Table `sporters_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(15) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `userAddress` VARCHAR(45) NULL,
  `postalCode` CHAR(5) NULL,
  `phoneNumber` CHAR(10) NULL,
  `city` VARCHAR(45) NULL,
  `confirmationToken` VARCHAR(60) NULL,
  `confirmedAt` DATE NULL,
  `userProfilePic` VARCHAR(100) NULL,
  `accountStatus` INT NULL DEFAULT 0,
  `membershipStatus` INT NULL DEFAULT 0,
  PRIMARY KEY (`userId`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sporters_db`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `adminPseudo` VARCHAR(45) NOT NULL,
  `adminPassword` VARCHAR(64) NOT NULL,
  `adminPrivilege` INT NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sporters_db`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`faq` (
  `faqId` INT NOT NULL AUTO_INCREMENT,
  `questions` LONGTEXT NOT NULL,
  `answers` LONGTEXT NOT NULL,
  `admin_idadmin` INT NOT NULL,
  PRIMARY KEY (`faqId`, `admin_idadmin`),
  CONSTRAINT `fk_faq_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `sporters_db`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_faq_admin1_idx` ON `sporters_db`.`faq` (`admin_idadmin` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`fields` (
  `fieldId` INT NOT NULL AUTO_INCREMENT,
  `fieldAddress` VARCHAR(45) NOT NULL,
  `fieldName` VARCHAR(45) NOT NULL,
  `fieldPostalCode` CHAR(5) NULL,
  `fieldSport` VARCHAR(45) NULL,
  `fieldSchedule` VARCHAR(45) NULL,
  `subField` VARCHAR(45) NULL,
  PRIMARY KEY (`fieldId`, `fieldAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sporters_db`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`games` (
  `gameId` INT NOT NULL AUTO_INCREMENT,
  `gameName` VARCHAR(45) NULL,
  `gameDate` DATE NULL,
  `gameSport` VARCHAR(45) NULL,
  `slotAvailable` INT NULL,
  `fields_fieldId` INT NOT NULL,
  `fields_fieldAddress` VARCHAR(45) NOT NULL,
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gameId`, `fields_fieldId`, `fields_fieldAddress`, `users_userId`, `users_email`),
  CONSTRAINT `fk_games_fields1`
    FOREIGN KEY (`fields_fieldId` , `fields_fieldAddress`)
    REFERENCES `sporters_db`.`fields` (`fieldId` , `fieldAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_users1`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_games_fields1_idx` ON `sporters_db`.`games` (`fields_fieldId` ASC, `fields_fieldAddress` ASC);

CREATE INDEX `fk_games_users1_idx` ON `sporters_db`.`games` (`users_userId` ASC, `users_email` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`events` (
  `eventId` INT NOT NULL AUTO_INCREMENT,
  `eventName` VARCHAR(45) NULL,
  `eventDate` DATE NULL,
  `eventSport` VARCHAR(45) NULL,
  `eventSlot` INT NULL,
  `eventPrice` FLOAT NULL,
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `fields_fieldId` INT NOT NULL,
  `fields_fieldAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`eventId`, `users_userId`, `users_email`, `fields_fieldId`, `fields_fieldAddress`),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_fields1`
    FOREIGN KEY (`fields_fieldId` , `fields_fieldAddress`)
    REFERENCES `sporters_db`.`fields` (`fieldId` , `fieldAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_events_users1_idx` ON `sporters_db`.`events` (`users_userId` ASC, `users_email` ASC);

CREATE INDEX `fk_events_fields1_idx` ON `sporters_db`.`events` (`fields_fieldId` ASC, `fields_fieldAddress` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`groups` (
  `groupId` INT NOT NULL AUTO_INCREMENT,
  `groupName` VARCHAR(45) NULL,
  `groupSport` VARCHAR(45) NULL,
  `groupOwner` VARCHAR(45) NULL,
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`groupId`, `users_userId`, `users_email`),
  CONSTRAINT `fk_groups_users1`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_groups_users1_idx` ON `sporters_db`.`groups` (`users_userId` ASC, `users_email` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`notifications` (
  `notifId` INT NOT NULL AUTO_INCREMENT,
  `notifMessage` LONGTEXT NULL,
  `notifType` VARCHAR(255) NULL,
  `notifDest` VARCHAR(255) NULL,
  PRIMARY KEY (`notifId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sporters_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`products` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(80) NULL,
  `productBrand` VARCHAR(45) NULL,
  `productType` VARCHAR(45) NULL,
  `productGender` VARCHAR(10) NULL,
  `productStock` INT NULL,
  `productPrice` FLOAT NULL,
  `productDescription` LONGTEXT NULL,
  `productSport` VARCHAR(45) NULL,
  `productScore` FLOAT NULL,
  `productImg` VARCHAR(100) NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sporters_db`.`games_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`games_history` (
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `games_gameId` INT NOT NULL,
  PRIMARY KEY (`users_userId`, `users_email`, `games_gameId`),
  CONSTRAINT `fk_users_has_games_users`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_games1`
    FOREIGN KEY (`games_gameId`)
    REFERENCES `sporters_db`.`games` (`gameId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_has_games_games1_idx` ON `sporters_db`.`games_history` (`games_gameId` ASC);

CREATE INDEX `fk_users_has_games_users_idx` ON `sporters_db`.`games_history` (`users_userId` ASC, `users_email` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`groups_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`groups_history` (
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `groups_groupId` INT NOT NULL,
  PRIMARY KEY (`users_userId`, `users_email`, `groups_groupId`),
  CONSTRAINT `fk_users_has_groups_users1`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_groups_groups1`
    FOREIGN KEY (`groups_groupId`)
    REFERENCES `sporters_db`.`groups` (`groupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_has_groups_groups1_idx` ON `sporters_db`.`groups_history` (`groups_groupId` ASC);

CREATE INDEX `fk_users_has_groups_users1_idx` ON `sporters_db`.`groups_history` (`users_userId` ASC, `users_email` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `products_productID` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `order_token` CHAR(5) NOT NULL,
  PRIMARY KEY (`order_id`, `users_userId`, `users_email`, `products_productID`),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_productID`)
    REFERENCES `sporters_db`.`products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_users1_idx` ON `sporters_db`.`orders` (`users_userId` ASC, `users_email` ASC);

CREATE INDEX `fk_orders_products1_idx` ON `sporters_db`.`orders` (`products_productID` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`notifications_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`notifications_history` (
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `notifications_notifId` INT NOT NULL,
  PRIMARY KEY (`users_userId`, `users_email`, `notifications_notifId`),
  CONSTRAINT `fk_users_has_notifications_users1`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_notifications_notifications1`
    FOREIGN KEY (`notifications_notifId`)
    REFERENCES `sporters_db`.`notifications` (`notifId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_has_notifications_notifications1_idx` ON `sporters_db`.`notifications_history` (`notifications_notifId` ASC);

CREATE INDEX `fk_users_has_notifications_users1_idx` ON `sporters_db`.`notifications_history` (`users_userId` ASC, `users_email` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`groups_notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`groups_notifications` (
  `notifications_notifId` INT NOT NULL,
  `groups_groupId` INT NOT NULL,
  PRIMARY KEY (`notifications_notifId`, `groups_groupId`),
  CONSTRAINT `fk_notifications_has_groups_notifications1`
    FOREIGN KEY (`notifications_notifId`)
    REFERENCES `sporters_db`.`notifications` (`notifId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_has_groups_groups1`
    FOREIGN KEY (`groups_groupId`)
    REFERENCES `sporters_db`.`groups` (`groupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_notifications_has_groups_groups1_idx` ON `sporters_db`.`groups_notifications` (`groups_groupId` ASC);

CREATE INDEX `fk_notifications_has_groups_notifications1_idx` ON `sporters_db`.`groups_notifications` (`notifications_notifId` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`admin_fields_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`admin_fields_history` (
  `admin_idadmin` INT NOT NULL,
  `fields_fieldId` INT NOT NULL,
  `fields_fieldAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_idadmin`, `fields_fieldId`, `fields_fieldAddress`),
  CONSTRAINT `fk_admin_has_fields_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `sporters_db`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_has_fields_fields1`
    FOREIGN KEY (`fields_fieldId` , `fields_fieldAddress`)
    REFERENCES `sporters_db`.`fields` (`fieldId` , `fieldAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_has_fields_fields1_idx` ON `sporters_db`.`admin_fields_history` (`fields_fieldId` ASC, `fields_fieldAddress` ASC);

CREATE INDEX `fk_admin_has_fields_admin1_idx` ON `sporters_db`.`admin_fields_history` (`admin_idadmin` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`events_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`events_history` (
  `users_userId` INT NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `events_eventId` INT NOT NULL,
  `events_groups_groupId` INT NOT NULL,
  `events_users_userId` INT NOT NULL,
  `events_users_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_userId`, `users_email`, `events_eventId`, `events_groups_groupId`, `events_users_userId`, `events_users_email`),
  CONSTRAINT `fk_users_has_events_users1`
    FOREIGN KEY (`users_userId` , `users_email`)
    REFERENCES `sporters_db`.`users` (`userId` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_events_events1`
    FOREIGN KEY (`events_eventId` , `events_users_userId` , `events_users_email`)
    REFERENCES `sporters_db`.`events` (`eventId` , `users_userId` , `users_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_has_events_events1_idx` ON `sporters_db`.`events_history` (`events_eventId` ASC, `events_groups_groupId` ASC, `events_users_userId` ASC, `events_users_email` ASC);

CREATE INDEX `fk_users_has_events_users1_idx` ON `sporters_db`.`events_history` (`users_userId` ASC, `users_email` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`groups_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`groups_events` (
  `groups_groupId` INT NOT NULL,
  `groups_users_userId` INT NOT NULL,
  `groups_users_email` VARCHAR(45) NOT NULL,
  `events_eventId` INT NOT NULL,
  `events_users_userId` INT NOT NULL,
  `events_users_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`groups_groupId`, `groups_users_userId`, `groups_users_email`, `events_eventId`, `events_users_userId`, `events_users_email`),
  CONSTRAINT `fk_groups_has_events_groups1`
    FOREIGN KEY (`groups_groupId` , `groups_users_userId` , `groups_users_email`)
    REFERENCES `sporters_db`.`groups` (`groupId` , `users_userId` , `users_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_has_events_events1`
    FOREIGN KEY (`events_eventId` , `events_users_userId` , `events_users_email`)
    REFERENCES `sporters_db`.`events` (`eventId` , `users_userId` , `users_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_groups_has_events_events1_idx` ON `sporters_db`.`groups_events` (`events_eventId` ASC, `events_users_userId` ASC, `events_users_email` ASC);

CREATE INDEX `fk_groups_has_events_groups1_idx` ON `sporters_db`.`groups_events` (`groups_groupId` ASC, `groups_users_userId` ASC, `groups_users_email` ASC);


-- -----------------------------------------------------
-- Table `sporters_db`.`cgu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sporters_db`.`cgu` (
  `cgu_id` INT NOT NULL AUTO_INCREMENT,
  `article` LONGTEXT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`cgu_id`, `admin_id`),
  CONSTRAINT `fk_cgu_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `sporters_db`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cgu_admin1_idx` ON `sporters_db`.`cgu` (`admin_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
